name: anemoi_weather
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  dartz: ^0.10.1
  equatable: ^2.0.5
  fl_chart: ^0.64.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.6.18
  geolocator: ^10.1.0
  get_it: ^7.6.4
  http: ^1.1.0
  intl: ^0.18.1
  mocktail: ^1.0.1
  package_info_plus: ^4.2.0
  permission_handler: ^11.0.1
  shared_preferences: ^2.2.2
  system_theme: ^2.3.1
  uuid: ^3.0.7

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - LICENSE.md

  fonts:
    - family: Weather
      fonts:
      - asset: assets/fonts/weather.ttf